In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [ ]:
import pandas as pd

In [ ]:
# Read the file from the drive
file_path = '/content/drive/My Drive/FinalDataset.tsv'
df = pd.read_csv(file_path, delimiter='\t', error_bad_lines=False)

<ipython-input-42-c4991a1ac648>:3: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(file_path, delimiter='\t', error_bad_lines=False)
Skipping line 17089: expected 15 fields, saw 22



In [ ]:
df.head()

marketplace  customer_id       review_id  product_id  product_parent  \
0          US     17747349  R2EI7QLPK4LF7U  B00U7LCE6A       106182406   
1          US     10956619  R1W5OMFK1Q3I3O  B00HRJMOM4       162269768   
2          US     13132245   RPZWSYWRP92GI  B00P31G9PQ       831433899   
3          US     35717248  R2WQWM04XHD9US  B00FGDEPDY       991059534   
4          US     17710652  R1WSPK2RA2PDEF  B00FZ0FK0U       574904556   

                                       product_title  product_category  \
0                           CCleaner Free [Download]  Digital_Software   
1                 ResumeMaker Professional Deluxe 18  Digital_Software   
2                          Amazon Drive Desktop [PC]  Digital_Software   
3         Norton Internet Security 1 User 3 Licenses  Digital_Software   
4  SecureAnywhere Intermet Security Complete 5 De...  Digital_Software   

   star_rating  helpful_votes  total_votes vine verified_purchase  \
0            4              0            0    N                 Y   
1            3              0            0    N                 Y   
2            1              1            2    N                 Y   
3            5              0            0    N                 Y   
4            4              1            2    N                 Y   

                               review_headline  \
0                                   Four Stars   
1                                  Three Stars   
2                                     One Star   
3                           Works as Expected!   
4  Great antivirus. Worthless customer support   

                                         review_body review_date  
0                                     So far so good  2015-08-31  
1                      Needs a little more work.....  2015-08-31  
2                                     Please cancel.  2015-08-31  
3                                 Works as Expected!  2015-08-31  
4  I've had Webroot for a few years. It expired a...  2015-08-31

In [ ]:
df_clean = df[['star_rating','review_body']]

In [ ]:
df_clean = df_clean.sample(frac=0.01)

In [ ]:
df_clean.shape

(199, 2)

In [ ]:
pip install SpellChecker

In [ ]:
!pip install pyspellchecker


In [ ]:
!pip install textblob

In [ ]:
  !python -m textblob.download_corpora

[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Package brown is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package conll2000 to /root/nltk_data...
[nltk_data]   Package conll2000 is already up-to-date!
[nltk_data] Downloading package movie_reviews to /root/nltk_data...
[nltk_data]   Package movie_reviews is already up-to-date!
Finished.


In [ ]:
import pandas as pd
import spacy
import string

# Ensure you're working on a copy to prevent SettingWithCopyWarning
df_clean = df_clean.copy()

# Drop NaN values or replace them with a default string
df_clean = df_clean.dropna(subset=['review_body'])

# Alternatively, to replace NaN with a default string: df_clean['lemmatized'].fillna('default_string', inplace=True)

# 1. Convert to lowercase
df_clean['lemmatized'] = df_clean['review_body'].str.lower()

# 2. Remove punctuation
df_clean['lemmatized'] = df_clean['lemmatized'].str.translate(str.maketrans('', '', string.punctuation))

# Load the spaCy model
nlp = spacy.load("en_core_web_sm")

# 3. Lemmatize
def lemmatize_text(text):
    doc = nlp(text)
    return ' '.join([token.lemma_ for token in doc])

df_clean['lemmatized'] = df_clean['lemmatized'].apply(lemmatize_text)

# 4. Remove Stop Words
def remove_stopwords(text):
    doc = nlp(text)
    return ' '.join([token.text for token in doc if not token.is_stop])

df_clean['lemmatized'] = df_clean['lemmatized'].apply(remove_stopwords)

# 5. Remove Digits
def remove_digits(text):
    return ''.join([char for char in text if not char.isdigit()])

df_clean['lemmatized'] = df_clean['lemmatized'].apply(remove_digits)

# Display the processed dataframe
print(df_clean)

       star_rating                                        review_body  \
17616            5  Great aroma and taste especially when first op...   
4635             5  Love this game.  Bought for pc because they ke...   
3600             1  I've been using Premiere Elements 9 for over 5...   
5513             1                         Never was able to use this   
14965            5  Thanks for an awesome gift for my mother she c...   
...            ...                                                ...   
7690             4  Fun game though I still like Dead Island bette...   
3896             5                                          Love it!!   
8363             5                     Great way to send a gift card.   
18270            4  This is a lot of charcoal. The packaging is no...   
14278            2  I have had the same problem with another revie...   

                                              lemmatized  
17616  great aroma taste especially open  month new c...  
4635 

In [ ]:
df_clean

star_rating                                        review_body  \
17616            5  Great aroma and taste especially when first op...   
4635             5  Love this game.  Bought for pc because they ke...   
3600             1  I've been using Premiere Elements 9 for over 5...   
5513             1                         Never was able to use this   
14965            5  Thanks for an awesome gift for my mother she c...   
...            ...                                                ...   
7690             4  Fun game though I still like Dead Island bette...   
3896             5                                          Love it!!   
8363             5                     Great way to send a gift card.   
18270            4  This is a lot of charcoal. The packaging is no...   
14278            2  I have had the same problem with another revie...   

                                              lemmatized  
17616  great aroma taste especially open  month new c...  
4635   love game    buy pc talk fallout want play xbo...  
3600   ve use premiere element   year teach stop moti...  
5513                                            able use  
14965  thank awesome gift mother station love portabl...  
...                                                  ...  
7690   fun game like dead island finger exact reasoni...  
3896                                                love  
8363                            great way send gift card  
18270  lot charcoal packaging ideal ve pour acticate ...  
14278  problem reviewer charger loud hissing hum nois...  

[199 rows x 3 columns]

In [ ]:
pip install transformers

In [ ]:
import pandas as pd
import torch
from torch.utils.data import DataLoader, Dataset
from transformers import BertTokenizer, BertForSequenceClassification, AdamW, get_linear_schedule_with_warmup

In [ ]:
# 2. Data Preprocessing for BERT
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [ ]:
null_count = df_clean.isnull().sum()

print(null_count)

star_rating    0
review_body    0
lemmatized     0
dtype: int64


In [ ]:
na_null_count = df_clean.isna().sum()

print(na_null_count)

star_rating    0
review_body    0
lemmatized     0
dtype: int64


In [ ]:
df_clean.describe()

star_rating
count   199.000000
mean      4.211055
std       1.327897
min       1.000000
25%       4.000000
50%       5.000000
75%       5.000000
max       5.000000

In [ ]:
column_data_types = df_clean.dtypes

print(column_data_types)

star_rating     int64
review_body    object
lemmatized     object
dtype: object


In [ ]:
# Find the index of the record with the maximum length
index_max_length = df_clean['lemmatized'].str.len().idxmax()

# Extract the record with the maximum length
record_max_length = df_clean.loc[index_max_length, 'lemmatized']

# Count the number of words
word_count = len(record_max_length.split())

print(f"Record number (index): {index_max_length}\n")
print(f"Record with the maximum length in 'text_column' is:\n\n{record_max_length}\n")
print(f"The record contains {word_count} words.")


Record number (index): 2515

Record with the maximum length in 'text_column' is:

videoidfbedeedcdbbe opportunity test microsoft window  operating system insider preview version know technical preview version release april  beta testing developer use april  want point thing general public look upgrade buy window  available july th  want lot info try good simple short readersbr br ░ ░ ░ ░ ░ info ░ ░ ░ ░ ░ br ❖ simple way describe window  combine strength window  window  allot people hate microsoft away old startup screen look picture kind bring windows br br ❖ window  available version home price  professional version  window  mobile smart phonesbr br ░ ░ ░ ░ ░ window  vs windows  ░ ░ ░ ░ ░ br ❖ start button backbr br ❖ cortana come pcsbr br ❖ microsoft edge new web browser windows br br user able annotate web page use fingerstylus keyboard inputbr spartan reading modebr cortana voice assistant integrate browserbr br ❖ end passwordbr br accord microsoft user able sign commonly use app l

In [ ]:
MAX_LEN = 128  # You can adjust this

class SentimentDataset(Dataset):
    def __init__(self, reviews, targets, tokenizer, max_len):
        self.reviews = reviews
        self.targets = targets
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.reviews)

    def __getitem__(self, item):
        review = str(self.reviews[item])
        target = self.targets[item]

        encoding = self.tokenizer.encode_plus(
            review,
            add_special_tokens=True,
            max_length=self.max_len,
            return_token_type_ids=False,
            padding='max_length',
            truncation=True,
            return_attention_mask=True,
            return_tensors='pt'
        )

        return {
            'review_text': review,
            'input_ids': encoding['input_ids'].flatten(),
            'attention_mask': encoding['attention_mask'].flatten(),
            'targets': torch.tensor(target, dtype=torch.long)
        }

In [ ]:
X = df_clean.lemmatized
y = df_clean.star_rating

In [ ]:
y = y.astype(int)

In [ ]:
y

17616    5
4635     5
3600     1
5513     1
14965    5
        ..
7690     4
3896     5
8363     5
18270    4
14278    2
Name: star_rating, Length: 199, dtype: int64

In [ ]:
# Initialize tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# Tokenize and get length
df_clean['num_tokens'] = df_clean['lemmatized'].apply(lambda x: len(tokenizer.tokenize(x)))

# Get the maximum number of tokens
max_tokens = df_clean['num_tokens'].max()

print(f"The maximum number of tokens in the column is: {max_tokens}")

The maximum number of tokens in the column is: 1569


In [ ]:
df_clean.to_csv("clean_data.csv")

In [ ]:
pip install --upgrade tensorflow


In [ ]:
pip install --upgrade tensorflow-gpu

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [ ]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 199 entries, 17616 to 14278
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   star_rating  199 non-null    int64 
 1   review_body  199 non-null    object
 2   lemmatized   199 non-null    object
 3   num_tokens   199 non-null    int64 
dtypes: int64(2), object(2)
memory usage: 15.9+ KB


In [ ]:
# Install the transformers library
!pip install transformers

import pandas as pd
import numpy as np
import re
from nltk.corpus import wordnet
from sklearn.model_selection import train_test_split
from transformers import BertTokenizer, TFBertForSequenceClassification
import tensorflow as tf
from sklearn.metrics import confusion_matrix, accuracy_score, precision_recall_fscore_support
from sklearn.utils import resample
import random

# Ensure you have the WordNet data downloaded
import nltk
nltk.download('wordnet')

# Text Cleaning
def clean_text(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'[^a-z0-9\s]', '', text)  # Remove special characters
    return text

df_clean['review_body'] = df_clean['review_body'].apply(clean_text)

# Data Augmentation using Synonym Replacement
def synonym_replace(text):
    words = text.split()
    new_words = words.copy()
    for i in range(len(words)):
        synonyms = wordnet.synsets(words[i])
        if synonyms and len(synonyms) > 0 and synonyms[0].lemmas():
            synonym_words = [lemma.name() for lemma in synonyms[0].lemmas()]
            synonym_choice = random.choice(synonym_words)
            new_words[i] = synonym_choice
    return ' '.join(new_words)

df_augmented = df_clean.copy()
df_augmented['review_body'] = df_augmented['review_body'].apply(synonym_replace)

# Combine original and augmented data
df_combined = pd.concat([df_clean, df_augmented])

# Adjust the labels to start from 0 instead of 1
def adjust_labels(rating):
    if rating in [1, 2]:
        return 0  # Negative
    elif rating == 3:
        return 1  # Neutral
    else:
        return 2  # Positive

df_combined['star_rating'] = df_combined['star_rating'].apply(adjust_labels)

# Split the data into training, validation, and test sets
train_df, temp_df = train_test_split(df_combined, test_size=0.3, random_state=42)
val_df, test_df = train_test_split(temp_df, test_size=0.5, random_state=42)

# Initialize the model and tokenizer
model = TFBertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=3)  # Assuming 3 labels: negative, neutral, positive
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# Tokenize and prepare the datasets
train_encodings = tokenizer(train_df['review_body'].tolist(), truncation=True, padding=True, max_length=128, return_tensors="tf")
train_labels = tf.convert_to_tensor(train_df['star_rating'].tolist())

val_encodings = tokenizer(val_df['review_body'].tolist(), truncation=True, padding=True, max_length=128, return_tensors="tf")
val_labels = tf.convert_to_tensor(val_df['star_rating'].tolist())

test_encodings = tokenizer(test_df['review_body'].tolist(), truncation=True, padding=True, max_length=128, return_tensors="tf")
test_labels = tf.convert_to_tensor(test_df['star_rating'].tolist())

# Convert encodings to tf.data.Dataset
train_dataset = tf.data.Dataset.from_tensor_slices((dict(train_encodings), train_labels)).shuffle(1000).batch(16)
val_dataset = tf.data.Dataset.from_tensor_slices((dict(val_encodings), val_labels)).batch(16)
test_dataset = tf.data.Dataset.from_tensor_slices((dict(test_encodings), test_labels)).batch(16)

# Define a custom loss function
loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

def compute_loss(labels, logits):
    return loss_object(labels, logits)

# Train the model
optimizer = tf.keras.optimizers.Adam(learning_rate=5e-5)
model.compile(optimizer=optimizer, loss=compute_loss, metrics=['accuracy'])
model.fit(train_dataset, validation_data=val_dataset, epochs=3)

# Predict on validation and test sets
val_predictions = np.argmax(model.predict(val_dataset).logits, axis=-1)
test_predictions = np.argmax(model.predict(test_dataset).logits, axis=-1)

# Compute metrics
val_confusion = confusion_matrix(val_df['star_rating'].tolist(), val_predictions)
test_confusion = confusion_matrix(test_df['star_rating'].tolist(), test_predictions)

val_accuracy = accuracy_score(val_df['star_rating'].tolist(), val_predictions)
test_accuracy = accuracy_score(test_df['star_rating'].tolist(), test_predictions)

val_precision, val_recall, val_f1, _ = precision_recall_fscore_support(val_df['star_rating'].tolist(), val_predictions, average='weighted')
test_precision, test_recall, test_f1, _ = precision_recall_fscore_support(test_df['star_rating'].tolist(), test_predictions, average='weighted')

# Print results
print("Validation Confusion Matrix:\n", val_confusion)
print("\nTest Confusion Matrix:\n", test_confusion)

print("\nValidation Metrics:")
print("Accuracy:", val_accuracy)
print("Precision:", val_precision)
print("Recall:", val_recall)
print("F1 Score:", val_f1)

print("\nTest Metrics:")
print("Accuracy:", test_accuracy)
print("Precision:", test_precision)
print("Recall:", test_recall)
print("F1 Score:", test_f1)



[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
All PyTorch model weights were used when initializing TFBertForSequenceClassification.

Some weights or buffers of the TF 2.0 model TFBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Epoch 1/3
18/18 [==============================] - 52s 622ms/step - loss: 0.7310 - accuracy: 0.7482 - val_loss: 0.6595 - val_accuracy: 0.7833
Epoch 2/3
18/18 [==============================] - 8s 451ms/step - loss: 0.6645 - accuracy: 0.7806 - val_loss: 0.6201 - val_accuracy: 0.7833
Epoch 3/3
4/4 [==============================] - 1s 136ms/step
Validation Confusion Matrix:
 [[ 0  0  3]
 [ 0  0 10]
 [ 0  0 47]]

Test Confusion Matrix:
 [[ 0  0  9]
 [ 0  0 11]
 [ 0  0 40]]

Validation Metrics:
Accuracy: 0.7833333333333333
Precision: 0.613611111111111
Recall: 0.7833333333333333
F1 Score: 0.6881619937694705

Test Metrics:
Accuracy: 0.6666666666666666
Precision: 0.4444444444444444
Recall: 0.6666666666666666
F1 Score: 0.5333333333333333


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
